const SUPABASE_URL='https://pwdswruaketzxkxlonqz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_2wpSz0wx9JnXl8AXCN5Djg_QTFS44lu';
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id); const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
function money(v){return '₦'+Number(v||0).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}
function showAuth(type){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.auth===type));$('loginForm').classList.toggle('hidden',type!=='login');$('registerForm').classList.toggle('hidden',type!=='register');$('authMessage').textContent=''}
async function loadDashboard(){const {data:{user}}=await supabase.auth.getUser();if(!user)return; $('authView').classList.add('hidden');$('dashboardView').classList.remove('hidden');
 let profile=null; const p=await supabase.from('profiles').select('first_name,surname,virtual_account_bank,virtual_account_name,virtual_account_number').eq('id',user.id).maybeSingle();profile=p.data;
 $('userName').textContent=((profile?.first_name||'Customer')+' '+(profile?.surname||'')).trim()+' 👋';$('bankName').textContent=profile?.virtual_account_bank||'Not available';$('accountName').textContent=profile?.virtual_account_name||'Not available';$('accountNumber').textContent=profile?.virtual_account_number||'Not available';
 const w=await supabase.from('wallets').select('balance').eq('id',user.id).maybeSingle();$('balance').textContent=money(w.data?.balance); 
}
async function init(){const {data:{session}}=await supabase.auth.getSession();if(session)loadDashboard();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showAuth(b.dataset.auth));
document.querySelectorAll('.show-pass').forEach(b=>b.onclick=()=>{const i=$(b.dataset.target);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});
$('loginForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='Signing in...';const {error}=await supabase.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error){$('authMessage').textContent=error.message;return}await loadDashboard();};
$('registerForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='Creating account...';const email=$('registerEmail').value.trim(), password=$('registerPassword').value;const {data,error}=await supabase.auth.signUp({email,password,options:{data:{first_name:$('firstName').value.trim(),surname:$('surname').value.trim(),phone:$('phone').value.trim()}}});if(error){$('authMessage').textContent=error.message;return}if(data.session)await loadDashboard();else $('authMessage').textContent='Account created. Check your email for verification.';};
$('logoutBtn').onclick=async()=>{await supabase.auth.signOut();$('dashboardView').classList.add('hidden');$('authView').classList.remove('hidden');showAuth('login');toast('Logged out')};
$('refreshBtn').onclick=()=>{loadDashboard();toast('Dashboard refreshed')};$('infoBtn').onclick=()=>toast('PrimeConnect • Fast • Secure • Reliable');
let balanceVisible=true;$('toggleBalance').onclick=()=>{balanceVisible=!balanceVisible;if(balanceVisible)loadDashboard();else $('balance').textContent='₦••••••'};
$('fundBtn').onclick=()=>toast('Wallet funding screen is ready for the next integration step.');$('createAccountBtn').onclick=()=>toast('Virtual account creation will use the existing Flutterwave Edge Function.');$('forgotBtn').onclick=()=>toast('Password reset will be connected to Supabase email recovery.');
function panel(type){const p=$('servicePanel');p.classList.remove('hidden');if(type==='airtime')p.innerHTML='<h3>📱 Buy Airtime</h3><label>Network<select><option>MTN</option><option>Airtel</option><option>Glo</option><option>9mobile</option></select></label><label>Phone<input placeholder="08012345678"></label><label>Amount<input type="number" min="50" placeholder="50"></label><button class="primary" onclick="toast(\'Airtime provider connection will use ClubKonnect.\')">CONTINUE</button>';else if(type==='data')p.innerHTML='<h3>🌐 Buy Data</h3><label>Network<select><option>MTN</option><option>Airtel</option><option>Glo</option><option>9mobile</option></select></label><label>Phone<input placeholder="08012345678"></label><label>Data Plan<select><option>Loading plans…</option></select></label><button class="primary" onclick="toast(\'Data plan API will use ClubKonnect.\')">CONTINUE</button>';else if(type==='history')p.innerHTML='<h3>🧾 Transaction History</h3><p class="muted">Your transaction history will be loaded from the existing PrimeConnect tables.</p>';else p.innerHTML='<h3>👤 Profile</h3><p class="muted">Your PrimeConnect profile is linked to Supabase.</p>';p.scrollIntoView({behavior:'smooth',block:'center'})}
document.querySelectorAll('.service').forEach(b=>b.onclick=()=>panel(b.dataset.service));document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const n=b.dataset.nav;if(n==='home')window.scrollTo({top:0,behavior:'smooth'});else panel(n==='services'?'airtime':n)});
supabase.auth.onAuthStateChange((event,session)=>{if(session)loadDashboard()});init();
